# Generated by Django 4.0.1 on 2022-01-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_candidates_bio_candidates_english_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
