# Generated by Django 4.0.1 on 2022-01-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_skills_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
