# Generated by Django 4.0.1 on 2022-01-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='cv',
            field=models.FileField(default=1, upload_to='candidate_resumes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidates',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.jobs'),
        ),
    ]
