# Generated by Django 4.0.1 on 2022-01-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_candidates_cv_candidates_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_Applying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='candidates_resumes/')),
                ('about', models.TextField(max_length=800)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobs')),
            ],
        ),
    ]
